apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
  labels:
    purpose : webserver
    env : production
spec:
  containers:
    - name: nginx
      image: nginx
    # - name: busybox
    #   image: busybox