apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80 # on pod
      port: 80 # Service (required field)
      nodePort: 30008 # Node port accessible on LAN
  selector:
    app: myapp
    type: front-end