apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: rsapp
    type: front-end
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        purpose : webserver
        env : production
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      env : production ## matches nginx-2 labels